title: Jonathan Jacobson
logo: /assets/img/selfie_circle.png
description: Aurora, CO 
  <a href="https://www.linkedin.com/in/jonathan-jacobson-8919a3291/"><img src="https://raw.githubusercontent.com/joja4479/joja4479.github.io/refs/heads/main/assets/img/linkedin%20logo.png" alt="HTML tutorial" style="width:32px;height:32px;opacity: 0.5;"></a>
github_username:  joja4479
linkedin_username: jonathan-jacobson-8919a3291
email: "joja4479@colorado.edu"

#show_downloads: true
theme: jekyll-theme-minimal
