title: jonathan jacobson
logo: /assets/img/IMG_2491(1).png
description: Aurora, CO
#show_downloads: true
theme: jekyll-theme-minimal

social-network-links:
  email: "joja4479@colorado.edu"
  github: joja4479
  linkedin: jonathan-jacobson-8919a3291


share-links-active:
  linkedin: true

