title: Jonathan Jacobson
logo: /assets/img/selfie_circle.png
description: Aurora, CO
github_username:  joja4479
linkedin_username: jonathan-jacobson-8919a3291
email: "joja4479@colorado.edu"

#show_downloads: true
theme: jekyll-theme-minimal
